### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by dragonlong** [dvlab-research/SMR#1]
Hi, 

Congratulations on the amazing work for CVPR21 paper! Just wonder when the code base will be released. Thanks!

Best,
Xiaolong

**Comment by tau-yihouxiang** [comment]
Hi, thank you for your attention! Since [Kaolin library](https://github.com/NVIDIAGameWorks/kaolin) has updated its version from v0.1 to v0.9. We are modifying our source code to match this version. It will be released soon.
