### ISSUE TITLE
Reported Metrics: How to test PCK, SSIM, FID, etc?

### ISSUE THREAD

**Issue by buutensil** [dvlab-research/SMR#11]
Hello, Hu, I failed to find out the testing code of the model.  And i can't figure out how to get the reported metrics in the paper with this code. Do I miss anything that is relevant?

**Comment by tau-yihouxiang** [comment]
Well, we have upgraded the rendering library from Kaolin v0.1 to v0.9, and this source code contains FID evaluation metrics and SSIM is easy to be involved.

**Comment by buutensil** [comment]
WHAT ABOUT PCK?

**Comment by tau-yihouxiang** [comment]
Our PCK evaluation was borrowed from https://github.com/NVlabs/UMR/blob/15ca8c87c158a238086ef01c9718c9c5773a6659/experiments/test_kp.py, this source code has been largely simplified, and we haven't transferred this evaluation from our original code.  I am busy combining NeRF with Mesh to improve the synthesized quality, the uniform evaluation of FID, SSIM, LPIPS, and PCK will be included. Thank you for your attention!

**Comment by buutensil** [comment]
I see. Looking forward to your new version code, and thanks for your hard working and details reply!
