### ISSUE TITLE
How do you ensure that the size of the reconstructed model is accurate?

### ISSUE THREAD

**Issue by yushengjiexy** [dvlab-research/SMR#14]
Hello, I downloaded the data set you provided. I am a beginner. I have a question. In the training set, there is only the original image and mask, and there is no scale information. How do you ensure that the size of the reconstructed model is accurate?

**Comment by tau-yihouxiang** [comment]
A single image can not reconstruct the absolute size of object, thus this paper reconstructs the relative size to the template sphere mesh.
