### ISSUE TITLE
关于代码的一些问题

### ISSUE THREAD

**Issue by M202071895** [dvlab-research/SMR#2]
您好，我阅读了您的“Self-Supervised_3D_Mesh_Reconstruction_From_Single_Images_CVPR_2021_paper”文章，深受启发，很想参考代码深入研究。我已经安装好了kaolin和其它所需要的库。
请问：
1. 您和团队是否有开源相关代码的打算
2. 正式开源的大致时间

**Comment by tau-yihouxiang** [comment]
Thank you for your attention. We plan to release the source code with kaolin 0.9.0 within the next 2 weeks.
