### ISSUE TITLE
Questions about GAN architecture and 2D-only supervision

### ISSUE THREAD

**Issue by yd-yin** [dvlab-research/SMR#4]
Hi! 
Thanks a lot for your great work, and thanks for releasing the code! I got some questions.

In the paper, I did not find the GAN architecture, while there is GAN loss in the code. Is GAN loss also part of this work?

\
Another question is about the implementation. Can I re-implement the 2D-only supervision by this code? 

I get an error if I set lambda_ic to 0, since `Xir` is rendered all the time, 
https://github.com/dvlab-research/SMR/blob/master/train.py#L547 
and `Ai` and `Aire` are used in losses, e.g.,
https://github.com/dvlab-research/SMR/blob/master/train.py#L577

Thanks a lot!

**Comment by tau-yihouxiang** [comment]
Yes, we fould that GAN loss is pretty useful during training. For 2D-only supervision, I will check it soon when lambda_ic = 0.
