### ISSUE TITLE
About the regularization term and other assumptions

### ISSUE THREAD

**Issue by yd-yin** [dvlab-research/SMR#6]
Hi! Thanks again for your great work!

Your code is clean and easy to understand. 

Noticed that there are some regularization terms, and if I'm correct, they are laplacian loss, flat loss and flip loss. It seems that laplacian loss and flat loss are related to the properties of a smooth mesh. 
What about the flip loss, then? Is it related to symmetry, or is there any assumption about the symmetry in this work?

Thanks a lot!

**Comment by tau-yihouxiang** [comment]
Actually, at first we didn't use flip loss as a regularization, while we then found that a weakly symmetric assumption can accelerate the convergence.
