### ISSUE TITLE
feature map for landmark consistency

### ISSUE THREAD

**Issue by junzhezhang** [dvlab-research/SMR#9]
Hi,

Thanks for the good work and the released work!

I would like to check with your on the implementation of the landmark consistency. In the paper, you mentioned that pixel-aligned feature map extracted from a U-net is used. But from what I can see from the code, it seems you are using a pretrained VGG for feature extraction. Would like to check with you, if VGG has the desirable pixel-alignment properties? If yes, which layer do you think works better? Or it is different from your original implementation for the paper?

Appreciate your reply. Thank you!

Best,
Junzhe

**Comment by tau-yihouxiang** [comment]
Yes, this is different from the original paper. The original Unet is much heavy than I expected when I clean the source code. Then I choose a layer (e.g., conv3) in pretrained VGG as the feature maps of landmarks, which is more lightweight and achieve similar performance.

**Comment by junzhezhang** [comment]
Hi Tao Hu,

Thanks a lot for the reply. I will give a try on the VGG conv3 :)

Btw for the Unet, where do you get the pretrained models, and may I know the architecture? Thanks:)

Best,
Junzhe
